[greenclip]
  blacklisted_applications = ["Qt Selection Owner for keepassxc"]
  enable_image_support = false
  history_file = "/home/antcc/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 15
  max_selection_size_bytes = 0
  static_history = ['''¯\_(ツ)_/¯''']
  trim_space_from_selection = false
  use_primary_selection_as_input = false
